export const metadata = {
    title: 'AbhikGanguly | About Page',
    description: 'Generated by create next app',
}

export default function AboutLayout({ children }) {
  return (
    <section>
        {children}
    </section>
  )
}
